### ISSUE TITLE
Error in parsing 

### ISSUE THREAD

**Issue by AhmedL99** [GreenWaves-Technologies/tiny_denoiser#2]
Hello, 
I am trying to run the tiny_denoiser example on the GAP9 module and I got this error:
`TypeError: _StoreAction.init() got an unexpected keyword argument 'completer_method'`

Is there something wrong with my configuration ? 
I just run the command `make clean all run [APP_MODE=0]` in the tiny_denoiser folder. 

This is the full output message: 
`script model/nntool_scripts/nntool_script_fp16_mixed_demo
APP_CFLAGS... -I/home/ahmed/Desktop/GAP9/tiny_denoiser/BUILD/GAP9_V2/GCC_RISCV_FREERTOS -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/rtos/sfu/include -O2 -s -mno-memcpy -fno-tree-loop-distribute-patterns  -Wno-incompatible-pointer-types -Icommon -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/libs/gap_lib/include/ -I. -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/libs/gap_lib/include -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/autotiler_v3/Emulation -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/autotiler_v3/Autotiler -IBUILD_MODEL_FP16MIXEDBIT -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/autotiler_v3/Generators/BilinearResizes -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/autotiler_v3/CNN_Libraries -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/autotiler_v3/DSP_Libraries -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/autotiler_v3/CNN_Libraries_fp16 -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/autotiler_v3/CNN_Libraries_SQ8 -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/autotiler_v3/CNN_Libraries_fp16 -I -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/autotiler_v3/DSP_Libraries -I/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/autotiler_v3/DSP_Libraries/LUT_Tables -IBUILD_MODEL_STFT -Isamples -DAT_MODEL_PREFIX=denoiser_dns -DAT_INPUT_HEIGHT=1 -DAT_INPUT_WIDTH=257  -DAT_INPUT_COLORS= -DSTACK_SIZE=4096 -DSLAVE_STACK_SIZE=2048  -DFREQ_FC=200 -DFREQ_CL=200 -DFREQ_SFU=200 -DVOLTAGE=650 -DAT_IMAGE= -DWAV_FILE=/home/ahmed/Desktop/GAP9/tiny_denoiser/samples/sample_0000.wav  -DIS_SFU=1  -DIS_INPUT_STFT=0 -DSTFT_FRAMES=10 -DFRAME_SIZE=400 -DFRAME_STEP=100 -DFRAME_NFFT=512 -DNUM_FRAME_OVERLAP=3 -DSAMPLING_FREQ=16000 -DAT_INPUT_WIDTH=257  -DAT_INPUT_HEIGHT=1 -DMAX_L2_BUFFER=1000000 -DDEMO=1 -DH_STATE_LEN=256 -DAPP_DIR="/home/ahmed/Desktop/GAP9/tiny_denoiser" -DSTD_FLOAT -DPERF -DSILENT -DGRU
rm -f -rf BUILD_MODEL_FP16MIXEDBIT
rm -rf /home/ahmed/Desktop/GAP9/tiny_denoiser/BUILD_MODEL_STFT
rm -rf BUILD*
mkdir BUILD_MODEL_FP16MIXEDBIT
cp model/denoiser_dns.onnx BUILD_MODEL_FP16MIXEDBIT/denoiser_dns.onnx
echo "GENERATING NNTOOL STATE FILE"
GENERATING NNTOOL STATE FILE
nntool -s model/nntool_scripts/nntool_script_fp16_mixed_demo BUILD_MODEL_FP16MIXEDBIT/denoiser_dns.onnx --use_lut_sigmoid --use_lut_tanh
Traceback (most recent call last):
  File "/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/nntool/scripts/nntool", line 107, in <module>
    main()
  File "/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/nntool/scripts/nntool", line 80, in main
    parser = create_parser()
  File "/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/nntool/scripts/nntool", line 75, in create_parser
    add_open_options(parser)
  File "/home/ahmed/Desktop/GAP9/gap_sdk_private-master/tools/nntool/nntool/interpreter/commands/open_parser.py", line 108, in add_open_options
    parser.add_argument('--out_ranges',
  File "/home/ahmed/.local/lib/python3.10/site-packages/cmd2/argparse_custom.py", line 866, in _add_argument_wrapper
    new_arg = orig_actions_container_add_argument(self, *args, **kwargs)
  File "/usr/lib/python3.10/argparse.py", line 1435, in add_argument
    action = action_class(**kwargs)
TypeError: _StoreAction.__init__() got an unexpected keyword argument 'completer_method'
make: *** [common/model_rules.mk:53: BUILD_MODEL_FP16MIXEDBIT/denoiser_dns.json] Error 1
`

**Comment by Pafrak** [comment]
Hello,
what's the python version that you are using?

**Comment by AhmedL99** [comment]
Python version: 3.10.6
OS version: Ubuntu 22.04

**Comment by Yaooooo** [comment]
Could you please remove the "[]" in your command?
So:
make clean all run APP_MODE=0

Yao Zhang
Greenwaves Technologies

**Comment by AhmedL99** [comment]
Hello! 

Thank you for your response! 

I tried to remove the "[]" but still got the same error, it is an error of compilation in the open_parser.py file

I may be wrong!

**Comment by AhmedL99** [comment]
I tried other examples using nntool and the same problem persists!
