### ISSUE TITLE
Demo mode (default config) does not seem to denoise anything

### ISSUE THREAD

**Issue by rsprabhu** [GreenWaves-Technologies/tiny_denoiser#5]
I followed the instructions and was able to build, flash and run on the GAP9 EVK + audio board. I can hear the audio coming into the microphone using headphones connected to HP jack. There is almost zero denoising happening (white noise and all noises I tried can be heard when I play it). Here are some other things I tried:
1. Using make menuconfig: change the precision to FP16. This resulted in scratchy (worse) audio. What am I missing?
2. Tried the denoisewav mode and changed the file to real_samples/phone_call.wav: this seemed to denoise.  So not sure why the demo wasn't working. 

Any hints? I am on a recent version of gap_sdk. I didn't have any visible build issues at all! yay!!

**Comment by rsprabhu** [comment]
Closing since I found tiny_denoiser_v2 repo. Doh

**Comment by Yaooooo** [comment]
And you need to use the slider on evk to enable/disable the denoiser.


*Yao ZHANG*Global Customer Success Director
APAC Business Development Director
Tel: 06.82.78.41.71
Mail: ***@***.***
Wechat: 453115693
-------------------------------------------------------------------------------------
[image: https://greenwaves-technologies.com/]
<https://greenwaves-technologies.com/>


rsprabhu ***@***.***>于2024年5月30日 周四20:02写道：

**Comment by rsprabhu** [comment]
Thanks, I guess I had the slider on the "let everything in" side.
